#!/bin/bash
# Git branch creator
# Change prefix to you initials
prefix="psh"

echo "Enter jira number: "

read jira_num

echo "Enter branch description (Letters and numbers only): "

read description

description=`echo "$description" | tr '[:upper:]' '[:lower:]'`

branch="${prefix}__sl-${jira_num}__${description// /-}"

eval "$(git checkout -b ${branch})"
